# Generated by Django 5.0.6 on 2024-06-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_alter_astronomyshow_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planetariumdome",
            options={
                "verbose_name": "Planetarium",
                "verbose_name_plural": "Planetariums",
            },
        ),
    ]
