# Generated by Django 5.0.6 on 2024-06-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0006_planetariumdome_price_per_seat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["id"],
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
    ]
