# Generated by Django 5.0.6 on 2024-06-06 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0007_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="description",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="astronomyshow",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="rows",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value cannot be greater than 100."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="seats_in_row",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value cannot be greater than 100."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="showtheme",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
