# Generated by Django 5.0.6 on 2024-06-06 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0008_alter_astronomyshow_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planetariumdome",
            name="price_per_seat",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Price cannot be negative."
                    ),
                    django.core.validators.MaxValueValidator(
                        30, message="Price exceeds the maximum allowed."
                    ),
                ],
            ),
        ),
    ]
