# Generated by Django 5.0.6 on 2024-06-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0009_alter_planetariumdome_price_per_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="price_per_seat",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="rows",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="seats_in_row",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="showsession",
            name="show_time",
            field=models.DateTimeField(
                help_text="Enter the show time in the format YYYY-MM-DD HH:MM:SS"
            ),
        ),
    ]
