# Generated by Django 5.0.6 on 2024-06-08 18:46

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0010_alter_astronomyshow_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.show_image_file_path
            ),
        ),
    ]
