# Generated by Django 5.0.6 on 2024-06-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0011_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
    ]
