# Generated by Django 5.0.6 on 2024-06-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0012_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("show_session", "row", "seat")},
        ),
    ]
