# Generated by Django 5.0.6 on 2024-06-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(default="@mykhailoyemets", max_length=255),
            preserve_default=False,
        ),
    ]
